### ISSUE TITLE
invitacion ROpenSpain

### ISSUE THREAD

**Issue by verajosemanuel** [rOpenSpain/LAU2boundaries4spain#2]
Excelente paquete. Muy útil para todos los que analizamos datos Españoles con R.
No se si conoces el proyecto ROpenSpain:  https://ropenspain.es/
Recopilamos paquetes para tratar datos abiertos en España con R. Nos gustaria mucho contar con el tuyo en nuestro repositorio.

Saludos

**Comment by perezp44** [comment]
Gracias. Sí, la verdad que es útil tener las geometrías correctas para cada año

Sí, conozco Ropenspain, una magnifica iniciativa, y nos parece bien que nuestro paquete figure allí, pero ¿qué hay que hacer?

saludos

**Comment by verajosemanuel** [comment]
Entra en la página y date de alta en el formulario de contacto. Iniciaremos el proceso.
Gracias

**Comment by perezp44** [comment]
Rellené hace más de 10 días el formulario. Recibí un mail dándome "acceso" a Ropenspain pero ninguna instrucción más.

**Comment by perezp44** [comment]
LAU2boundaries4Spain ya está alojado en rOpenSpain
